Historiske data har vi kun pr 1. januar. Det vil sige at vi tager 1 kvartals tallet for de nye data.

In [353]:
import requests
import pandas as pd

# Retrieves population data from all municipalities

## Defining calls to Statistic Denmark API
# 2008 to date
FOLK1A = 'https://api.statbank.dk/v1/data/FOLK1A/CSV?valuePresentation=CodeAndValue&OMR%C3%85DE=*&Tid=*'

# 2005 to 2009
BEF1A07 = "https://api.statbank.dk/v1/data/BEF1A07/CSV?valuePresentation=CodeAndValue&OMR%C3%85DE=*&Tid=*"

# 1979 to 2006
BEF1A = "https://api.statbank.dk/v1/data/BEF1A/CSV?valuePresentation=CodeAndValue&OMR%C3%85DE=*&Tid=*"

# Retrieving data
FOLK1A_data = pd.read_csv(FOLK1A, sep = ";")
BEF1A07_data = pd.read_csv(BEF1A07, sep = ";")
BEF1A_data = pd.read_csv(BEF1A, sep = ";")

In [354]:
# cleaning the data
# FOLK1A needs additional step

def clean_pop_data(df):
    df['muni_code'] = df['OMRÅDE'].str.extract(r'(\d{3})')   # extracting municipality code
    df['muni_name'] = df['OMRÅDE'].str.extract(r'(\d{3}\s+(.*))')[1] # extracting municipalit name
    df['year'] = df['TID'].str.split().str[0]
    df = df\
        .drop(columns=["OMRÅDE", 'TID'])\
        .rename(columns={'INDHOLD':'pop'})
    return df

FOLK1A_data = clean_pop_data(FOLK1A_data)
BEF1A_data = clean_pop_data(BEF1A_data)
BEF1A07_data = clean_pop_data(BEF1A07_data)

In [355]:
FOLK1A_data["muni_code"] = FOLK1A_data["muni_code"].astype("Int64")
BEF1A_data["muni_code"] = BEF1A_data["muni_code"].astype("Int64")
BEF1A07_data["muni_code"] = BEF1A07_data["muni_code"].astype("Int64")

In [356]:
# additional cleaning of FOLK1A data
FOLK1A_data = FOLK1A_data[FOLK1A_data['year'].str.endswith('1')]
FOLK1A_data['year'] = FOLK1A_data['year'].str.replace('K1', "")

Så skal vi have pillet dem ud der skal pilles ud. Vi skal have alt fra FOLK1A det er fra 1.1 08.

Så skal vi have alt fra BEF1A. det er frem til 2006

Og så skal vi have 2007 fra bef1a_o7

Hm... I bef1a07 har de de nye koder. Dem der også bruges i folk1a. Det er dem vi skal have fat på. Og vi har 
en komplet liste. Så er der de gamle...

pd.concat([FOLK1A_data, BEF1A07_data])

Vi starter med de nye tal.

In [357]:
pop_data = pd.concat([FOLK1A_data, BEF1A07_data]).reset_index(drop = True).drop_duplicates()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1995 entries, 0 to 2202
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pop        1995 non-null   int64
 1   muni_code  1995 non-null   Int64
 2   muni_name  1995 non-null   object
 3   year       1995 non-null   object
dtypes: Int64(1), int64(1), object(2)
memory usage: 79.9+ KB

In [358]:
#Nu har vi populaionsdata for 2007 og frem
# dette er de gamle.

# vi indlæser vores data på hvilke nye muni_codes de har
konkordans = pd.read_csv("../nye_og_gamle_kommuner.csv")


konkordans['old_muni_code'] = konkordans['old_muni_code'].astype('Int64')
konkordans['muni_code'] = konkordans['muni_code'].astype('Int64')
konkordans

BEF1A_data['muni_code'] = BEF1A_data['muni_code'].astype('Int64')
nye = pop_data[["muni_code", 'year', "pop"]]
gamle = BEF1A_data\
    .merge(konkordans, how='left', left_on = 'muni_code', right_on = 'old_muni_code')\
    .groupby(["muni_code_x", "year"])["pop"].agg("sum").reset_index().rename(columns={'muni_code_x':'muni_code'})
gamle["muni_code"] = gamle["muni_code"].astype('Int64')

In [359]:
totalen = pd.concat([nye, gamle])

In [369]:

totalen.astype('int64').query("muni_code == 161").sort_values("year")

      muni_code  year    pop
280         161  1979  19612
281         161  1980  19573
282         161  1981  19645
283         161  1982  19548
284         161  1983  19552
285         161  1984  19542
286         161  1985  19696
287         161  1986  19559
288         161  1987  19901
289         161  1988  19896
290         161  1989  19749
291         161  1990  19747
292         161  1991  19844
293         161  1992  19923
294         161  1993  20237
295         161  1994  20274
296         161  1995  20263
297         161  1996  20181
298         161  1997  20178
299         161  1998  20104
300         161  1999  20102
301         161  2000  20229
302         161  2001  20278
303         161  2002  20412
304         161  2003  20586
305         161  2004  20793
1735        161  2005  20785
306         161  2005  20785
307         161  2006  20699
1736        161  2006  20699
1737        161  2007  20618
176         161  2008  20673
177         161  2009  21008
178         161  2010  21296
179         161  2011  21384
180         161  2012  21650
181         161  2013  21869
182         161  2014  22066
183         161  2015  22357
184         161  2016  22461
185         161  2017  22528
186         161  2018  22663
187         161  2019  22615
188         161  2020  23128
189         161  2021  23380
190         161  2022  23514
191         161  2023  23635