In [7]:
import os
import pandas as pd

In [8]:
os.chdir(r'C:\Users\lakj\Documents\GitHub\isds2023\Boliga data\unique_data')

In [9]:
files = os.listdir()
dfs = []
for i in files:
    df = pd.read_csv(i)
    dfs.append(df)

C:\Users\lakj\AppData\Local\Temp\ipykernel_22064\3950082257.py:4: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(i)
C:\Users\lakj\AppData\Local\Temp\ipykernel_22064\3950082257.py:4: DtypeWarning: Columns (9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(i)
C:\Users\lakj\AppData\Local\Temp\ipykernel_22064\3950082257.py:4: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(i)
C:\Users\lakj\AppData\Local\Temp\ipykernel_22064\3950082257.py:4: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(i)

In [11]:
all_df = pd.concat(dfs)

In [12]:
all_df.head()

,municipality,housing_type,address,zip_code,town,purchase_amount,date_of_sale,type_of_sale,square_meters,square_meters_price,rooms,year_of_construction,The percentage difference between the latest bid price and the sale price
0,101,Ejerlejlighed,"Allersgade 2, 4. th",2200,København N,3950000,30-12-2022,Alm. Salg,97,40722,3,1990,-1%
1,101,Ejerlejlighed,"Birketinget 2F, st. 602",2300,København S,1695000,30-12-2022,Alm. Salg,45,37667,1,1970,NaN
2,101,Ejerlejlighed,"Himmerlandsvej 17, st. th",2720,Vanløse,1775000,30-12-2022,Alm. Salg,55,32273,2,1934,-6%
3,101,Ejerlejlighed,"Randersgade 49, 3. th",2100,København Ø,4050000,30-12-2022,Alm. Salg,70,57857,3,1893,-3%
4,101,Villa,Dyssevænget 4B,2700,Brønshøj,1100000,30-12-2022,Fam. Salg,100,11000,5,1964,NaN

In [ ]:
def get_square_meter_price(row): # Get the prices for a square meters, for examle 13158
        new_str = re.split('m²', row)[1].replace('.', '')
        return new_str.split()[0]
    
    
all_df['square_meters_price'] = df['m² & Kr. / m²'].apply(lambda x : get_square_meter_price(x))

In [16]:
for i in all_df['square_meters_price']:
    if i == 'kr/':
        print (i)

kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/
kr/

In [83]:
os.chdir(r'C:\Users\lakj\Documents\GitHub\isds2023\Boliga data\data')

In [84]:
files = [i for i in os.listdir() if i.endswith('.csv')]

In [85]:
dfs = []
for i in files:
    df = pd.read_csv(i, low_memory=False)
    dfs.append(df)

In [86]:
all_df = pd.concat(dfs).reset_index(drop=True)

In [92]:
import re
import numpy as np
def get_square_meter_price(row): # Get the prices for a square meters, for examle 13158
    strings = re.split('m²', row)[1].replace('.', '')
    strings = ''.join(re.findall('\d', strings))
    try:
        return int(strings)
    except ValueError:
        return np.NaN

all_df['square_meter_price'] = all_df['m² & Kr. / m²'].apply(lambda row: get_square_meter_price(row))

In [96]:
all_df[all_df['square_meter_price'].isna()]

,Boligtype & Adresse,Købesum,Dato & Type,m² & Kr. / m²,Vær.,Byggeår,Den procentuelle forskel mellem seneste udbudspris og salgsprisen %,Unnamed: 7,square_meter_price
642432,Villa VVilla Chr Hauchs Alle 8A 3500 Værløse,3.447.500 kr.,11-01-2009Alm. Salg,62 m² kr/m²,1,1960,NaN,Aktuel værdi,NaN
724489,Villa VVilla Strøbjergvej 32 3600 Frederikssund,5.650.000 kr.,20-05-2021Alm. Salg,441 m² kr/m²,10,1952,-3%,Aktuel værdi,NaN
745094,Villa VVilla Strøbjergvej 32 3600 Frederikssund,1.750.000 kr.,24-04-1998Alm. Salg,441 m² kr/m²,10,1952,NaN,Aktuel værdi,NaN
828950,Villa VVilla Vængetvej 22 3630 Jægerspris,575.000 kr.,28-02-2014Alm. Salg,159 m² kr/m²,4,0,-17%,Aktuel værdi,NaN
829383,Villa VVilla Vængetvej 22 3630 Jægerspris,1.100.000 kr.,22-04-2013Alm. Salg,159 m² kr/m²,4,0,58%,Aktuel værdi,NaN
932528,Villa VVilla Vestergade 15 4000 Roskilde,3.250.000 kr.,26-03-2014Alm. Salg,213 m² kr/m²,6,2019,-18%,Aktuel værdi,NaN
1089872,Villa VVilla Posthusvej 5 4593 Eskebjerg,1.050.000 kr.,10-02-2017Alm. Salg,79 m² kr/m²,2,1925,NaN,Aktuel værdi,NaN
1113783,Villa VVilla Posthusvej 5 4593 Eskebjerg,463.000 kr.,10-02-1992Alm. Salg,79 m² kr/m²,2,1925,NaN,Aktuel værdi,NaN
1133574,Villa VVilla Brovej 8A 4241 Vemmelev,100.000 kr.,08-08-2022Alm. Salg,130 m² kr/m²,4,1937,NaN,Aktuel værdi,NaN
1134998,Villa VVilla Brovej 8A 4241 Vemmelev,65.000 kr.,12-09-2021Alm. Salg,130 m² kr/m²,4,1937,NaN,Aktuel værdi,NaN
1183305,Villa VVilla Hasselvænget 33 4652 Hårlev,885.000 kr.,09-05-2022Alm. Salg,172 m² kr/m²,4,0,NaN,Aktuel værdi,NaN
1183820,Villa VVilla Skrænten 32 4600 Køge,1.870.000 kr.,09-05-2021Alm. Salg,178 m² kr/m²,6,2022,4%,Aktuel værdi,NaN
1184386,Villa VVilla Lerskovvej 20A 4652 Hårlev,295.000 kr.,29-07-2020Alm. Salg,131 m² kr/m²,4,2021,NaN,Aktuel værdi,NaN
1184397,Villa VVilla Kystvejen 170 4671 Strøby,3.400.000 kr.,21-07-2020Alm. Salg,169 m² kr/m²,4,2021,-3%,Aktuel værdi,NaN
1187555,Villa VVilla Kystvejen 170 4671 Strøby,130.000 kr.,06-06-2013Fam. Salg,169 m² kr/m²,4,2021,NaN,Aktuel værdi,NaN
1188473,Villa VVilla Kystvejen 170 4671 Strøby,600.000 kr.,26-05-2010Alm. Salg,169 m² kr/m²,4,2021,NaN,Aktuel værdi,NaN
1194837,Villa VVilla Kystvejen 170 4671 Strøby,320.000 kr.,14-12-1996Fam. Salg,169 m² kr/m²,4,2021,NaN,Aktuel værdi,NaN
1195686,Villa VVilla Skrænten 32 4600 Køge,380.000 kr.,05-03-1995Alm. Salg,178 m² kr/m²,6,2022,NaN,Aktuel værdi,NaN
1308538,Villa VVilla Bygaden 28 4800 Nykøbing F,150.000 kr.,12-12-2022Fam. Salg,150 m² kr/m²,6,2023,NaN,Aktuel værdi,NaN
1312385,Villa VVilla Bygaden 28 4800 Nykøbing F,150.000 kr.,14-06-2020Alm. Salg,150 m² kr/m²,6,2023,-25%,Aktuel værdi,NaN
1312623,Villa VVilla Sundvej 9 4862 Guldborg,1.055.000 kr.,07-04-2020Alm. Salg,205 m² kr/m²,4,0,-12%,Aktuel værdi,NaN
1392011,Rækkehus RRækkehus Kong Gustafsvej 47 3730 Nexø,1.400.000 kr.,30-01-2011Alm. Salg,85 m² kr/m²,4,0,NaN,Aktuel værdi,NaN
1396164,Rækkehus RRækkehus Kong Gustafsvej 47 3730 Nexø,150.000 kr.,12-03-2006Alm. Salg,85 m² kr/m²,4,0,NaN,Aktuel værdi,NaN
1407182,Rækkehus RRækkehus Kong Gustafsvej 47 3730 Nexø,450.000 kr.,21-01-1996Fam. Salg,85 m² kr/m²,4,0,NaN,Aktuel værdi,NaN
1407346,Villa VVilla Isingen 20 5500 Middelfart,907.500 kr.,09-11-2022Alm. Salg,188 m² kr/m²,5,2023,NaN,Aktuel værdi,NaN
1504115,"Ejerlejlighed EEjerlejlighed Kongegade 22C, 1 ...",30.200.000 kr.,08-01-2018Andet,134 m² kr/m²,0,1906,NaN,Aktuel værdi,NaN
1546356,"Ejerlejlighed EEjerlejlighed Vandværksvej 24, ...",6.275.000 kr.,29-02-2016Alm. Salg,240 m² kr/m²,4,1912,-5%,Aktuel værdi,NaN
1555317,"Ejerlejlighed EEjerlejlighed Vandværksvej 24, ...",2.570.169 kr.,13-02-2013Alm. Salg,240 m² kr/m²,4,1912,NaN,Aktuel værdi,NaN
1561656,"Ejerlejlighed EEjerlejlighed Vandværksvej 24, ...",4.800.000 kr.,04-08-2010Alm. Salg,240 m² kr/m²,4,1912,NaN,Aktuel værdi,NaN
1669035,Villa VVilla Sehestedparken 26 5450 Otterup,777.101 kr.,21-08-2022Alm. Salg,180 m² kr/m²,4,0,NaN,Aktuel værdi,NaN
1669038,Villa VVilla Sehestedparken 28 5450 Otterup,670.111 kr.,18-08-2022Alm. Salg,196 m² kr/m²,6,0,NaN,Aktuel værdi,NaN
2063305,"Ejerlejlighed EEjerlejlighed Låsbygade 55, st....",3.550.000 kr.,21-05-2019Alm. Salg,72 m² kr/m²,-2,1885,NaN,Aktuel værdi,NaN
2070233,"Ejerlejlighed EEjerlejlighed Låsbygade 55, st....",3.500.000 kr.,29-04-2015Alm. Salg,72 m² kr/m²,-2,1885,NaN,Aktuel værdi,NaN
2100794,"Ejerlejlighed EEjerlejlighed Låsbygade 55, st....",2.200.000 kr.,02-07-1997Alm. Salg,72 m² kr/m²,-2,1885,NaN,Aktuel værdi,NaN
2124536,Villa VVilla Horskær Mosevej 9 7100 Vejle,305.000 kr.,08-03-2018Alm. Salg,151 m² kr/m²,3,0,-23%,Aktuel værdi,NaN
2148799,Villa VVilla Horskær Mosevej 9 7100 Vejle,440.000 kr.,27-05-2006Alm. Salg,151 m² kr/m²,3,0,NaN,Aktuel værdi,NaN
2186040,Villa VVilla Kaj Munks Vej 11 7400 Herning,4.100.000 kr.,11-08-2020Andet,571 m² kr/m²,5,1977,NaN,Aktuel værdi,NaN
2293026,Villa VVilla Vegavej 23 8400 Ebeltoft,1.685.000 kr.,02-05-2021Alm. Salg,158 m² kr/m²,5,0,NaN,Aktuel værdi,NaN
2330424,Rækkehus RRækkehus Birkedommervej 4B 8500 Grenaa,3.500.000 kr.,17-12-2003Alm. Salg,162 m² kr/m²,4,1925,NaN,Aktuel værdi,NaN
2337070,Rækkehus RRækkehus Birkedommervej 4B 8500 Grenaa,1.388.000 kr.,11-12-1995Alm. Salg,162 m² kr/m²,4,1925,NaN,Aktuel værdi,NaN
3023246,Villa VVilla Søndre Kirkevej 1 9940 Læsø,1.250.000 kr.,08-11-2022Alm. Salg,178 m² kr/m²,5,0,-3%,Aktuel værdi,NaN
3024078,Villa VVilla Søndre Kirkevej 1 9940 Læsø,1.400.000 kr.,26-03-2006Alm. Salg,178 m² kr/m²,5,0,NaN,Aktuel værdi,NaN
3024876,Villa VVilla Søndre Kirkevej 1 9940 Læsø,306.000 kr.,07-06-1993Fam. Salg,178 m² kr/m²,5,0,NaN,Aktuel værdi,NaN